name: periodic health check

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: check app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-w6g2.onrender.com
          max-attempts: 3 
          retry-delay: 5s 